name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Terraform Lint
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Test runner
        run: echo "Le runner fonctionne, le code est là :" && ls
