name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Terraform Lint (TFLint)
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Préparer le dossier de rapports
        run: mkdir -p reports

      - name: Lancer TFlint
        run: |
          set -o pipefail
          tflint --init
          tflint --recursive --format compact | tee reports/tflint-raw.txt

      - name: Formater le rapport en Markdown
        if: always()
        run: |
          {
            echo "# Rapport TFLint"
            echo
            echo "_Généré le $(date)_"
            echo
            echo '```'
            cat reports/tflint-raw.txt
            echo '```'
          } > reports/tflint-report.md

      - name: Conserver le rapport TFLint
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tflint-report
          path: reports/tflint-report.md

  secrets:
    name: Détection de secrets (Gitleaks)
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code (historique complet)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Préparer le dossier de rapports
        run: mkdir -p reports

      - name: Lancer Gitleaks
        run: |
          set -o pipefail
          docker run --rm -v "$PWD:/repo" -w /repo ghcr.io/gitleaks/gitleaks:latest detect --source . --report-format sarif --report-path reports/gitleaks.sarif -redact -v | tee reports/gitleaks-report.txt

      - name: Conserver les rapports Gitleaks
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleak-report
          path: reports/
